export type SourceCategory = "City documents" | "News" | "Recreation records" | "Health & recreation" | "Historical records" | "Community statements" | "Candidate statements";

export const candidateQuestions = [
  "Would you support pausing removal of the Westwood Lake indoor tennis facility until the City has completed public consultation and assessed whether year-round indoor tennis can feasibly be retained? Please explain.",
  "Would you support evaluating nonprofit, lease, partnership or other operating models before the indoor facility is removed?",
  "What role should year-round indoor racquet-sport facilities play in Nanaimo's long-term recreation planning?",
];

export const sources = [
  {
    title: "Candidate nomination documents",
    publisher: "City of Nanaimo",
    date: "September 11, 2026",
    category: "City documents" as SourceCategory,
    url: "https://www.nanaimo.ca/your-government/elections/candidate-nomination-documents",
    summary: "The City's official candidate document page identifies declared candidates for mayor and council. It is the reference used for the candidate tracker.",
    primary: true,
  },
  {
    title: "2026 General Local Election",
    publisher: "City of Nanaimo",
    date: "2026",
    category: "City documents" as SourceCategory,
    url: "https://www.nanaimo.ca/your-government/elections",
    summary: "The City's election page confirms that general voting takes place October 17, 2026. It also provides voting and candidate information.",
    primary: true,
  },
  {
    title: "City of Nanaimo expands Westwood Lake Park with new land acquisition",
    publisher: "City of Nanaimo",
    date: "September 16, 2026",
    category: "City documents" as SourceCategory,
    url: "https://www.nanaimo.ca/NewsReleases/NR260916CityOfNanaimoExpandsWestwoodLakeParkWithNewLandAcquisition.html",
    summary: "The City's announcement confirms the property acquisition, states that the club will cease operations and that the bubble will be removed, and says future uses will be shaped through planning and community engagement.",
    primary: true,
  },
  {
    title: "Nanaimo's Westwood Lake expands through City land purchase",
    publisher: "NanaimoNewsNOW",
    date: "September 16, 2026",
    category: "News" as SourceCategory,
    url: "https://nanaimonewsnow.com/2026/09/16/nanaimos-westwood-lake-expands-through-city-land-purchase/",
    summary: "Reports the City's $2.88-million purchase of the 2.85-acre property. It also reports the November 1 club closure and planned removal of the tennis bubble.",
    primary: false,
  },
  {
    title: "Land acquisition increases area of Westwood Lake Park",
    publisher: "Nanaimo News Bulletin",
    date: "September 17, 2026",
    category: "News" as SourceCategory,
    url: "https://nanaimobulletin.com/2026/09/17/land-acquisition-increases-area-of-westwood-lake-park-in-nanaimo/",
    summary: "Covers the acquisition and reports December 18 as the expected possession date. It describes the City's intended longer-term planning process.",
    primary: false,
  },
  {
    title: "City purchases Westwood Tennis Club property to add to park",
    publisher: "My Coast Now",
    date: "September 17, 2026",
    category: "News" as SourceCategory,
    url: "https://www.mycoastnow.com/94783/news/municipal-news/city-of-nanaimo/city-of-nanaimo-purchases-westwood-tennis-club-property-to-add-to-park/",
    summary: "Reports that the City does not plan to operate the site as a tennis club. Outdoor courts are expected to remain available for public use.",
    primary: false,
  },
  {
    title: "Nanaimo expanding Westwood Lake Park with land purchase",
    publisher: "CHEK News",
    date: "September 16, 2026",
    category: "News" as SourceCategory,
    url: "https://cheknews.ca/nanaimo-expanding-westwood-lake-park-with-2-88m-land-purchase-1348211/",
    summary: "Provides independent coverage of the purchase price, property size and City rationale. Includes the Mayor's public statement about the acquisition.",
    primary: false,
  },
  {
    title: "Westwood Lake expansion raises concerns over loss of indoor tennis",
    publisher: "CBC News",
    date: "September 20, 2026",
    category: "News" as SourceCategory,
    url: "https://www.youtube.com/watch?v=oCYB8IJWwFI",
    summary: "CBC News reports on the planned removal of the Westwood Lake tennis bubble, community concerns about the loss of year-round programming, and the City's longer-term consideration of future racquet-sport facilities at Beban Park.",
    primary: false,
  },
  {
    title: "More than just a beautiful game",
    publisher: "British Columbia Medical Journal",
    date: "September 2026",
    category: "Health & recreation" as SourceCategory,
    url: "https://bcmj.org/editorials/more-just-beautiful-game",
    summary: "An editorial by Inderveer Mahal, MD, CCFP, discussing the public-health value of social connection, accessible sport and community infrastructure. It provides broader context for community recreation and does not address the Westwood Lake facility specifically.",
    primary: false,
  },
  {
    title: "Urge Nanaimo to preserve Westwood Lake indoor tennis courts",
    publisher: "Change.org",
    date: "September 17, 2026",
    category: "Community statements" as SourceCategory,
    url: "https://www.change.org/p/urge-nanaimo-to-preserve-westwood-lake-indoor-tennis-courts",
    summary: "A community-organized petition asking Nanaimo City Council to preserve the indoor courts while alternative operating models are considered. This is a community advocacy source, not a City document.",
    primary: true,
  },
  {
    title: "Nanaimo Builds for the Future: plan update",
    publisher: "City of Nanaimo",
    date: "September 17, 2025",
    category: "City documents" as SourceCategory,
    url: "https://www.nanaimo.ca/docs/your-government/projects/rpt_fa250917nanaimobuildsforthefutureplanupdatewithattachments.pdf",
    summary: "Staff report, pp. 8–11: a possible Beban Park indoor pavilion could accommodate tennis alongside other sports. Its chart gives a potential 2027–2032 borrowing window for the broader Beban Park Master Plan, with low confidence in cost. It is not a construction or opening schedule.",
    primary: true,
  },
  {
    title: "October 6, 2025 Regular Council meeting summary",
    publisher: "City of Nanaimo",
    date: "October 6, 2025",
    category: "City documents" as SourceCategory,
    url: "https://www.nanaimo.ca/your-government/city-council/council-meetings/summaries/lists/summaries/october-6-2025-regular-council-summary",
    summary: "Council endorsed priority projects and deferred consideration of Beban Park improvements until detailed design and costing of those priorities are complete.",
    primary: true,
  },
  {
    title: "October 20, 2025 Regular Council meeting summary",
    publisher: "City of Nanaimo",
    date: "October 20, 2025",
    category: "City documents" as SourceCategory,
    url: "https://www.nanaimo.ca/your-government/city-council/council-meetings/summaries/lists/summaries/october-20-2025-regular-council-summary",
    summary: "Council denied the proposed residential rezoning for 2367 Arbot Road, the Westwood Lake Tennis Club property. This decision preceded the City's 2026 purchase.",
    primary: true,
  },
  {
    title: "2367 Arbot Road rezoning application and staff report",
    publisher: "City of Nanaimo",
    date: "October 20, 2025",
    category: "Historical records" as SourceCategory,
    url: "https://www.nanaimo.ca/whatsbuilding/Folder/RA000512",
    summary: "Official property record for rezoning application RA000512, including the staff report and application documents. The application status is denied.",
    primary: true,
  },
  {
    title: "Townhouse rezoning rejected near Westwood Lake",
    publisher: "NanaimoNewsNOW",
    date: "October 21, 2025",
    category: "Historical records" as SourceCategory,
    url: "https://nanaimonewsnow.com/2025/10/21/not-a-good-fit-townhouse-rezoning-rejected-near-nanaimos-westwood-lake/",
    summary: "Reports Council's 7–2 vote against first reading of an earlier townhouse rezoning proposal for the property. This predates and is separate from the City's acquisition.",
    primary: false,
  },
];

export const unknowns = [
  "Structural assessment and remaining useful life of the indoor bubble",
  "Estimated removal cost",
  "Annual operating and maintenance cost",
  "Replacement cost for comparable indoor courts",
  "Current indoor-court utilization and number of users",
  "Whether nonprofit, lease or partnership operating models have been formally assessed",
];

export const timeline = [
  { date: "Sep 16", year: "2026", title: "Acquisition announced", text: "The City announces its purchase of the Westwood Lake Tennis Club property.", status: "Occurred", source: sources[2] },
  { date: "Sep 17", year: "2026", title: "Community response begins", text: "A community-organized public petition asks the City to preserve the indoor facility while alternatives are assessed.", status: "Occurred", source: sources[9] },
  { date: "Oct 17", year: "2026", title: "Municipal election", text: "Nanaimo holds its general local election.", status: "Scheduled", source: sources[1] },
  { date: "Nov 1", year: "2026", title: "Expected club closure", text: "Westwood Lake Tennis Club is expected to cease operations.", status: "Expected", source: sources[2] },
  { date: "Dec 18", year: "2026", title: "Expected possession", text: "The City is expected to take possession of the property.", status: "Expected", source: sources[4] },
  { date: "Future", year: "", title: "Planning and engagement", text: "The City has indicated that broader planning and community engagement will shape future uses.", status: "Future", source: sources[2] },
];
